# Generated by Django 6.0.3 on 2026-03-15 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="handle",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="handleは英数字とアンダースコアのみ使用できます。",
                        regex="^[a-zA-Z0-9_]+$",
                    )
                ],
            ),
        ),
    ]
