# Generated by Django 5.2.12 on 2026-03-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('users', '0003_customuser_bio'),
	]

	operations = [
		migrations.CreateModel(
			name='Follow',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=20)),
				('requested_at', models.DateTimeField(auto_now_add=True)),
				('accepted_at', models.DateTimeField(blank=True, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_edges', to=settings.AUTH_USER_MODEL)),
				('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_edges', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'ordering': ['-created_at'],
				'constraints': [
					models.UniqueConstraint(fields=('follower', 'followee'), name='unique_follow_edge'),
					models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='follow_no_self_follow'),
				],
			},
		),
		migrations.CreateModel(
			name='FollowEvent',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('action', models.CharField(choices=[('request', 'request'), ('accept', 'accept'), ('reject', 'reject'), ('unfollow', 'unfollow'), ('remove_by_block', 'remove_by_block')], max_length=30)),
				('actor_handle_snapshot', models.CharField(blank=True, max_length=30)),
				('target_handle_snapshot', models.CharField(blank=True, max_length=30)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_events_as_actor', to=settings.AUTH_USER_MODEL)),
				('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_events_as_target', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'ordering': ['-created_at'],
			},
		),
	]