# Generated by Django 5.2.12 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('users', '0004_follow_followevent'),
	]

	operations = [
		migrations.AddField(
			model_name='customuser',
			name='is_private_account',
			field=models.BooleanField(default=False),
		),
	]