# Generated by Django 5.2.12 on 2026-03-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('users', '0005_customuser_is_private_account'),
	]

	operations = [
		migrations.CreateModel(
			name='UserBlock',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				(
					'blocked',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='blocked_by_edges',
						to='users.customuser',
					),
				),
				(
					'blocker',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='blocking_edges',
						to='users.customuser',
					),
				),
			],
			options={
				'ordering': ['-created_at'],
			},
		),
		migrations.AddConstraint(
			model_name='userblock',
			constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block'),
		),
		migrations.AddConstraint(
			model_name='userblock',
			constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_no_self_block'),
		),
	]
