# Generated by Django 6.0.3 on 2026-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userblock"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "status", "-accepted_at", "-created_at"],
                name="idx_following_list",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["followee", "status", "-accepted_at", "-created_at"],
                name="idx_follower_list",
            ),
        ),
    ]
