# Generated by Django 6.0.3 on 2026-03-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0003_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="visibility",
            field=models.CharField(
                choices=[("public", "public"), ("private", "private")],
                default="public",
                max_length=20,
            ),
        ),
    ]
