# Generated by Django 6.0.3 on 2026-03-16 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0006_character_owner_characterworldentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["world", "-created_at", "-id"], name="idx_post_world_timeline"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="idx_post_author_recent"
            ),
        ),
    ]
